---
- name: Install Collabora and Haproxy Docker compose
  hosts: NGINX
  become: yes
  vars:
    nx_image      : nextcloud:22-fpm
    nx_folder     : /opt/build/nextcloud
    nx_folder_end : /var/www/html
    nx_image      : nextcloud:22-fpm
    nx_port_def   : 9000
    nx_data       : data

  tasks:

  - name: Mkdir Build
  #  ansible.builtin.shell: mkdir -p {{ nx_folder }}/html | mkdir -p {{ nx_folder }}/data
    ansible.builtin.shell: mkdir -p {{ nx_folder }}/data

  - name: Copy docker_compose.yml
    ansible.builtin.template:
      src: "./php-fpm/docker-compose.j2"
      dest: "{{ nx_folder }}/docker-compose.yml"

  - name: Restart Docker PHP-FPM
    ansible.builtin.shell: /usr/local/bin/docker-compose -f {{ nx_folder }}/docker-compose.yml down &&  /usr/local/bin/docker-compose -f {{ nx_folder }}/docker-compose.yml up -d && /usr/local/bin/docker-compose -f {{ nx_folder }}/docker-compose.yml ps | grep nextcloud | awk '{print $1}'
    register: output

  - debug:
      var: output.stdout_lines

#  - name: Copy PHP-FPM files
#    ansible.builtin.shell: /usr/bin/docker cp  {{ output.stdout_lines | lower }}:{{ nx_folder_end }} {{ nx_folder }}

  - name: Copy docker_compose.yml
    ansible.builtin.template:
      src: "./php-fpm/docker-compose-latest.j2"
      dest: "{{ nx_folder }}/docker-compose-latest"
