---
- name: Install Collabora and Haproxy Docker compose
#  hosts: NGINX
  hosts: NC_BL
  become: yes
  vars:
    ha_image      : haproxy:1.8-alpine
    ha_folder     : /opt/build/collabora
    ha_mon_port   : 8084
    cb_image      : collabora/code
    cb_port_def   : 9980
    cb_port_1     : 9981
    cb_port_2     : 9982
  tasks:
    - name: Mkdir Build
      ansible.builtin.shell: mkdir -p {{ ha_folder }}/haproxy/ssl

    - name: Copy docker_compose.yml
      ansible.builtin.template:
        src: "./collabora/docker-compose.j2"
        dest: "{{ ha_folder }}/docker-compose.yml"

    - name: Copy Haproxy Conf
      ansible.builtin.template:
        src: "./collabora/haproxy.j2"
        dest: "{{ ha_folder }}/haproxy/haproxy.cfg"
    - name: Copy ssl files Haproxy
      copy:
        src: "./collabora/ssl/"
        dest: "{{ ha_folder }}/haproxy/ssl"

    - name: Restart Docker Collabora
      ansible.builtin.shell: /usr/local/bin/docker-compose -f {{ ha_folder }}/docker-compose.yml down &&  /usr/local/bin/docker-compose -f {{ ha_folder }}/docker-compose.yml up -d && /usr/local/bin/docker-compose -f {{ ha_folder }}/docker-compose.yml ps
      register: output

    - debug:
        var: output.stdout_lines
